### ISSUE TITLE
Crash report [0.7.4] - custom esphome_text capability

### ISSUE THREAD

**Issue by Baldhor** [Baldhor/Homey-ESPhome-Enhanced#46]
**Describe the bug**
Received a crash report for version 0.7.4 (current version):
```
Error: Invalid Capability: text
    at Remote Process
    at HomeyClient.emit (/node_modules/@athombv/homey-apps-sdk-v3/lib/HomeyClient.js:44:23)
    at Object.emit (/node_modules/@athombv/homey-apps-sdk-v3/manager/drivers.js:78:54)
    at Object.emit (/node_modules/@athombv/homey-apps-sdk-v3/lib/Driver.js:126:50)
    at VirtualDevice.addCapability (/node_modules/@athombv/homey-apps-sdk-v3/lib/Device.js:446:25)
    at /app/drivers/esphome-wizard/driver.js:317:46
    at Array.forEach (<anonymous>)
    at /app/drivers/esphome-wizard/driver.js:315:44
    at Array.forEach (<anonymous>)
    at /app/drivers/esphome-wizard/driver.js:303:31
    at PairSession._triggerEvent (/node_modules/@athombv/homey-apps-sdk-v3/lib/PairSession.js:80:12)
```

**Comment by Baldhor** [comment]
It is meant to be the custom capability "esphome_text", obviously configuration is wrong and to be honest I'm unsure the implementation is fully correct ...

**Comment by Baldhor** [comment]
refer to #48
