### ISSUE TITLE
Crash report - delete physical device by id when expecting object

### ISSUE THREAD

**Issue by Baldhor** [Baldhor/Homey-ESPhome-Enhanced#50]
**Describe the bug**
Received a crash report:
```
Note: this e-mail is sent because an unhandledRejection occurred in your app. Make sure to catch all errors, this might crash your app in the future. Stack trace attached below:

  TypeError: Cannot read properties of null (reading 'id')
    at Function._delete (/drivers/esphome-wizard/physical-device-manager.js:106:62)
    at PhysicalDevice.<anonymous> (/drivers/esphome-wizard/driver.js:306:43)
    at PhysicalDevice.emit (node:events:526:28)
    at PhysicalDevice.disconnectedListener (/drivers/esphome-wizard/physical-device.js:355:14)
    at Client.<anonymous> (/drivers/esphome-wizard/physical-device.js:88:44)
    at Client.emit (node:events:526:28)
    at Client.errorListener (/drivers/esphome-wizard/client.js:183:14)
    at EsphomeNativeApiClient.nativeApiClient.on.signal (/drivers/esphome-wizard/client.js:137:58)
    at EsphomeNativeApiClient.emit (node:events:526:28)
    at EsphomeNativeApiConnection.<anonymous> (/node_modules/@2colors/esphome-native-api/lib/client.js:60:18)
```

**To Reproduce**
unknown

**Expected behavior**
no crash report :)

**Comment by Baldhor** [comment]
fix live
